yamlversion: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
  
  redis:
    image: "redis:alpine"
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf



