version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - flask-app

  flask-app:
    build: .
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000-5002:5000-5002"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
